// ─── Events ──────────────────────────────────────────────────────────────────
// Speaking and DJ events — past and upcoming.
// Set upcoming: true for future events; they'll be highlighted on the site.
// Type: "speaking" | "dj"

import type { Event } from "@/lib/types";

export const events: Event[] = [

  // ── Speaking ──────────────────────────────────────────────────────────────

  // Upcoming
  {
    id: "earthfest-2026",
    title: "Earthfest",
    type: "speaking",
    date: "2026-06-25",
    venue: "",
    location: "London, England, UK",
    upcoming: true,
  },
  {
    id: "climate-live-2026",
    title: "Climate Live x Earth Percent",
    type: "speaking",
    date: "2026-04-08",
    venue: "Brian Eno's Studio",
    location: "London, England, UK",
    upcoming: true,
  },

  // Past
  {
    id: "eps-2026",
    title: "Event Production Showcase",
    type: "speaking",
    date: "2026-02-27",
    venue: "ExCeL London",
    location: "London, England, UK",
    upcoming: false,
    url: "https://www.eventproductionshow.co.uk/",
  },
  {
    id: "gei18-2026",
    title: "Green Events & Innovations Conference (GEI18)",
    type: "speaking",
    date: "2026-02-25",
    venue: "Royal Lancaster Hotel",
    location: "London, England, UK",
    upcoming: false,
    url: "https://www.agreenerfuture.com/gei",
  },
  {
    id: "un-accelerator-city-2025",
    title: "United Nations Accelerator City: Expedition Two",
    type: "speaking",
    date: "2025-11-28",
    venue: "",
    location: "Liverpool, England, UK",
    upcoming: false,
    url: "https://cultureliverpool.co.uk/news/liverpool-hosts-expedition-two-next-phase-of-un-accelerator-city-for-climate-action/",
  },
  {
    id: "bdme-2025",
    title: "Berlin Dance Music Event",
    type: "speaking",
    date: "2025-05-09",
    venue: "",
    location: "Berlin, DE",
    upcoming: false,
    url: "https://berlin-dance-music-event.com/",
  },
  {
    id: "music-sustainability-summit-2025",
    title: "Music Sustainability Summit",
    type: "speaking",
    date: "2025-04-15",
    venue: "",
    location: "Los Angeles, California, USA",
    upcoming: false,
    url: "https://www.musicsustainability.org/summit",
  },
  {
    id: "ilmc-37",
    title: "International Live Music Conference (ILMC 37)",
    type: "speaking",
    date: "2025-03-06",
    venue: "Royal Garden Hotel",
    location: "London, England, UK",
    upcoming: false,
    url: "https://37.ilmc.com/speaker/ross-patel/",
  },
  {
    id: "gei17-2025",
    title: "Green Events & Innovations Conference (GEI17)",
    type: "speaking",
    date: "2025-02-26",
    venue: "Royal Lancaster Hotel",
    location: "London, England, UK",
    upcoming: false,
    url: "https://www.agreenerfuture.com/blog-agf/gei17-welcomes-music-and-climate-heavyweights-as-we-announce-the-full-agenda",
  },
  {
    id: "ade-2024",
    title: "Amsterdam Dance Event (ADE)",
    type: "speaking",
    date: "2024-10-16",
    venue: "Various venues",
    location: "Amsterdam, NL",
    upcoming: false,
    url: "https://www.amsterdam-dance-event.nl",
  },
  {
    id: "ilmc-36",
    title: "International Live Music Conference (ILMC 36)",
    type: "speaking",
    date: "2024-03-07",
    venue: "Royal Garden Hotel",
    location: "London, England, UK",
    upcoming: false,
    url: "https://36.ilmc.com/speaker/ross-patel/",
  },

  // ── DJ / Polyamoross ──────────────────────────────────────────────────────

  {
    id: "club-love-loco-klub-2026",
    title: "Club Love",
    type: "dj",
    date: "2026-02-21",
    venue: "Loco Klub",
    location: "Bristol, England, UK",
    upcoming: false,
    url: "https://clubloveltd.com",
  },
  {
    id: "come-bye-festival-2025",
    title: "Come By Festival",
    type: "dj",
    date: "2025-09-11",
    venue: "",
    location: "Abergavenny, Wales, UK",
    upcoming: false,
    url: "https://www.instagram.com/come_bye_festival/",
  },
  {
    id: "lost-village-2025",
    title: "Lost Village",
    type: "dj",
    date: "2025-08-23",
    venue: "Lost Village Festival",
    location: "Lincolnshire, England, UK",
    upcoming: false,
    url: "https://lostvillagefestival.com/",
  },
  {
    id: "just-jack-motion-2025",
    title: "Just Jack - 24hr Motion Closing Party",
    type: "dj",
    date: "2025-07-19",
    venue: "Motion",
    location: "Bristol, England, UK",
    upcoming: false,
    url: "https://crackmagazine.net/2025/07/motion-closing-event-just-jack/",
  },
  {
    id: "carbon-project-2025",
    title: "The Carbon Trust",
    type: "dj",
    date: "2025-07-01",
    venue: "Regent's University",
    location: "London, England, UK",
    upcoming: false,
    url: "https://www.carbontrust.com/",
  },
  {
    id: "club-love-2025",
    title: "Club Love",
    type: "dj",
    date: "2025-03-22",
    venue: "Loco Klub",
    location: "Bristol, England, UK",
    upcoming: false,
    url: "https://clubloveltd.com",
  },
  {
    id: "lovrs-lisbon-2025",
    title: "LOVRS",
    type: "dj",
    date: "2025-01-09",
    venue: "Drama Bar",
    location: "Lisbon, PT",
    upcoming: false,
  },
  {
    id: "club-love-members-2024",
    title: "Club Love",
    type: "dj",
    date: "2024-05-17",
    venue: "The Loco Klub",
    location: "Bristol, England, UK",
    upcoming: false,
  },
  {
    id: "queens-yard-2024",
    title: "Queen's Yard Summer Party",
    type: "dj",
    date: "2024-05-04",
    venue: "Hackney Wick Multiple Venues",
    location: "London, England, UK",
    upcoming: false,
  },
  {
    id: "body-movements-winter-2024",
    title: "Body Movements",
    type: "dj",
    date: "2024-02-03",
    venue: "Various Venues",
    location: "London, England, UK",
    upcoming: false,
  },
  {
    id: "jess-hands-friends-2024",
    title: "Jess Hands & Friends",
    type: "dj",
    date: "2024-01-26",
    venue: "Number 90",
    location: "London, England, UK",
    upcoming: false,
  },
  {
    id: "no-strings-2023",
    title: "No Strings",
    type: "dj",
    date: "2023-09-09",
    venue: "Dare 2 Club",
    location: "Bristol, England, UK",
    upcoming: false,
  },
  {
    id: "body-movements-festival-2023",
    title: "Body Movements Festival",
    type: "dj",
    date: "2023-07-29",
    venue: "Various Venues",
    location: "London, England, UK",
    upcoming: false,
  },
  {
    id: "risen-festival-2023",
    title: "Risen Festival",
    type: "dj",
    date: "2023-04-01",
    venue: "Various venues",
    location: "London, England, UK",
    upcoming: false,
  },
  {
    id: "studio-9294-mar-2023",
    title: "Studio 9294",
    type: "dj",
    date: "2023-03-25",
    venue: "Studio 9294",
    location: "London, England, UK",
    upcoming: false,
  },
  {
    id: "ugly-cry-2023",
    title: "Ugly Cry Records Presents",
    type: "dj",
    date: "2023-03-25",
    venue: "Studio 9294",
    location: "London, England, UK",
    upcoming: false,
  },
  {
    id: "discotheke-2023",
    title: "DISCOTHEKE",
    type: "dj",
    date: "2023-03-11",
    venue: "Apotheke",
    location: "Los Angeles, California, USA",
    upcoming: false,
  },
];
